<?php

/**
 * @file
 * ldnddev Gallery Module file.
 */

/**
 * Implements hook_theme().
 */
function ldnddev_gallery_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ldnddev_gallery' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__ldnddev_gallery_image' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__ldnddev_gallery_video' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__ldnddev_gallery' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__ldnddev_gallery_item' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__ldnddev_gallery_image' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__ldnddev_gallery_video' => [
      'base hook' => 'paragraph',
    ],
    'media__remote_video' => [
      'base hook' => 'paragraph',
    ],
    'field__media__remote_video' => [
      'base hook' => 'paragraph',
    ],
  ];
}
